MEDICAL_CATEGORY = {
    "Unknown": "Unclassified or unspecified medical documents",
    "Cardiology": "Medical specialty concerning heart and cardiovascular system disorders",
    "Hematology": "Branch of medicine focused on blood disorders and hematopoietic system",
    "Oncology": "Clinical discipline dedicated to cancer diagnosis, treatment and research",
    "Endocrinology": "Medical field studying hormone-related disorders and glandular systems",
    "Respiratory": "Specialty dealing with lung diseases and respiratory tract disorders",
    "Allergy": "Clinical practice focused on hypersensitivity reactions and immune responses",
    "Dermatology": "Medical specialty treating skin, hair and nail disorders",
    "Nephrology": "Branch of internal medicine addressing kidney diseases",
    "Gastroenterology": "Medical discipline concerning digestive system disorders",
    "Rheumatology": "Specialty focused on autoimmune and musculoskeletal disorders",
    "Otorhinolaryngology": "Surgical-medical specialty for ear, nose and throat disorders",
    "Anesthesiology": "Medical practice centered on pain management and perioperative care",
    "Biochemistry": "Laboratory medicine field analyzing bodily fluids and metabolic processes",
    "Pharmacology": "Scientific discipline studying drug actions and therapeutic uses",
    "Psychiatry": "Medical specialty diagnosing and treating mental health disorders",
    "Microbiology": "Laboratory science identifying infectious agents and antimicrobial resistance",
    "Physiology": "Basic medical science studying normal bodily functions",
    "Pathology": "Diagnostic discipline investigating disease mechanisms through tissue analysis",
    "Obstetrics": "Medical-surgical specialty managing pregnancy and childbirth",
    "Gynecology": "Women's health specialty focusing on reproductive system disorders",
    "Surgery": "Invasive therapeutic discipline performing operative procedures",
    "Emergency": "Acute care specialty handling trauma and life-threatening conditions",
    "Orthopedics": "Surgical specialty correcting musculoskeletal system deformities",
    "Neurology": "Medical discipline treating nervous system disorders",
    "Urology": "Surgical specialty managing urinary tract and male reproductive system",
    "Anatomy": "Fundamental medical science studying body structures",
    "Genetics": "Medical field investigating inherited disorders and genomic variations",
    "Radiology": "Diagnostic specialty utilizing medical imaging technologies",
    "Ophthalmology": "Surgical-medical specialty treating eye and vision disorders",
    "Odontology": "Dental medicine field addressing oral health and maxillofacial disorders",
    "Pediatrics": "Medical specialty focused on child and adolescent health",
    "Geriatrics": "Clinical practice managing health conditions in elderly patients",
    "Nursing": "Healthcare profession providing patient care and medical support",
    "Chemistry": "Laboratory science analyzing biochemical substances and reactions",
    "Psychology": "Behavioral science studying mental processes and cognitive functions",
}

FINANCE_CATEGORY = {
    "Monetary Economics": "Economic field focusing on central banking, money supply, and interest rate mechanisms",
    "Fiscal Policy & Public Finance": "Policy domain analyzing government spending, taxation systems, and public debt management",
    "Macroeconomic Theory": "Theoretical framework studying economy-wide phenomena including growth cycles and inflation dynamics",
    "International Finance": "Global finance discipline examining cross-border capital flows and exchange rate regimes",
    "Financial Markets & Instruments": "Market structure domain covering equity, debt, and derivative investment vehicles",
    "Microeconomic Foundations": "Behavioral analysis field investigating individual/firm decision-making and market equilibria",
    "Economic History & Crises": "Historical research on financial crises and long-term economic development patterns",
    "Development Economics": "Growth strategy field addressing poverty reduction and emerging market industrialization",
    "Behavioral & Institutional Economics": "Interdisciplinary study of psychological/social factors influencing economic choices",
    "Unknown": "Unclassifiable or interdisciplinary financial research topics"
}
